# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: UK PDC Geophysics Book
author: UK PDC
logo: images/logo.jpg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache
  timeout: 100
  
repository:
  url: https://github.com/antarctica/PDC_GeophysicsBook # Online location of your book
  path_to_book: book  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)
  
launch_buttons:
  notebook_interface        : classic  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : https://binder.pangeo.io  # The URL of the BinderHub (e.g., https://mybinder.org or https://binder.pangeo.io)
  jupyterhub_url            : ""  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
  thebe                     : false  # Add a thebe button to pages (requires the repository to run on Binder)
  colab_url                 : "" # The URL of Google Colab (https://colab.research.google.com)
  
html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true  # Whether to add an "Suggest edit" button to pages. If `true`, repository information in repository: must be filled in

